### ISSUE TITLE
Support for Ninja build system?

### ISSUE THREAD

**Issue by Hi-Angel** [jcs090218/setup-emacs#104]
Hello, I'm [setting up a CI](https://github.com/ankurdave/color-identifiers-mode/pull/114#issuecomment-1497868019) for an Emacs package, and stumbled upon that I can't run a `ninja tests` because, of the trio: Linux, Mac OS, Windows, only the latter for some reason has [Ninja](https://github.com/ninja-build/ninja).

Would it be too complicated to add installation of ninja package for the other two as well?

**Comment by jcs090218** [comment]
Are you looking for https://github.com/marketplace/actions/setup-ninja?

```yaml
...

    steps:
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          # ninja version to download. Default: 1.10.0
          version: 1.10.0

...
```

Another way to avoid this, is to specify OS specific step, like:

```yaml
    - name: Check cmake
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: "cmake --version"
```

Above just an random example. It will only install CMake on Linux and macOS.
